### ISSUE TITLE
Cannot do forward pass: inputs not set

### ISSUE THREAD

**Issue by tguructa** [samuelchapas/LSTMEncDecDL4J#1]
Just tied your sample and getting this issue. appreciate your help.

Exception in thread "main" java.lang.IllegalStateException: Cannot do forward pass: inputs not set
      at org.deeplearning4j.nn.graph.vertex.impl.MergeVertex.doForward(MergeVertex.java:76)
      at org.deeplearning4j.examples.recurrent.encdec.EncoderDecoderLSTM.output(EncoderDecoderLSTM.java:406)
      at org.deeplearning4j.examples.recurrent.encdec.EncoderDecoderLSTM.test(EncoderDecoderLSTM.java:387)
      at org.deeplearning4j.examples.recurrent.encdec.EncoderDecoderLSTM.train(EncoderDecoderLSTM.java:328)
      at org.deeplearning4j.examples.recurrent.encdec.EncoderDecoderLSTM.run(EncoderDecoderLSTM.java:239)
      at org.deeplearning4j.examples.recurrent.encdec.EncoderDecoderLSTM.main(EncoderDecoderLSTM.java:209)

Ubuntu
Deeplearning4j alpah arelease
cuda 9

**Comment by samuelchapas** [comment]
hi @tguructa , sorry for late response I haven't taken care of the repo.
This issue was solved in the examples of deepLearning4j after making this observations to the issues of the repo, here is the fix https://github.com/deeplearning4j/dl4j-examples/pull/684/commits/2b117e2c81ca80acbb382469d07ac90729f9c325.
Here is the original issue> https://github.com/deeplearning4j/deeplearning4j/issues/5043.
Please tell me if you solved it.

**Comment by samuelchapas** [comment]
By the way, are you developing a next word predictor? if so, we should make contributions to develop an opensource SpellingChecker and Next WordPredictions by using deepLearning4j. You can tell us what do you think!
